# Generated by Django 4.2.7 on 2024-03-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
