# Generated by Django 4.2.7 on 2024-03-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapi', '0002_partner_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='status',
        ),
    ]
